include:
  - local: "/.gitlab/ci/variables/defaults.yml"
  - local: "/.gitlab/ci/templates/docker-steps.yml"
  - local: "/.gitlab/ci/templates/ui-build-steps.yml"
  - local: "/.gitlab/ci/templates/ui-docker-steps.yml"
  - local: "/.gitlab/ci/templates/chart-update-steps.yml"
  - local: "/.gitlab/ci/templates/deploy-steps.yml"
  - local: "/.gitlab/ci/templates/verify-steps.yml"
  - local: "/.gitlab/ci/templates/rollback-steps.yml"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - release
  - deploy
  - verify
  - rollback

build:
  extends: .ui_build

build_main:
  extends: .ui_build_main

push:
  extends: .ui_push

update_chart:
  extends: .update_chart

deploy_service:
  extends:
    - .deploy_service
    - .deploy_release_rules

verify_e2e:
  extends:
    - .verify_e2e
    - .deploy_release_rules

rollback_deploy:
  extends:
    - .rollback_deploy
    - .deploy_release_rules
