include:
  - local: "/.gitlab/ci/variables/defaults.yml"
  - local: "/.gitlab/ci/templates/docker-steps.yml"
  - local: "/.gitlab/ci/templates/ui-build-steps.yml"
  - local: "/.gitlab/ci/templates/ui-docker-steps.yml"
  - local: "/.gitlab/ci/templates/chart-update-steps.yml"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - release

build:
  extends: .ui_build

build_main:
  extends: .ui_build_main

push:
  extends: .ui_push

update_chart:
  extends: .update_chart
